### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by maximusblade** [DraperStudio/Laravel-Questionable#1]
Nice to have:

- List all users (that have answered) a question
- Delete all answers per question
- Delete all questions per Model
- $post->hasAnswered(Model $user) ?
- $post->hasQuestioned(Model $user) ?

**Comment by DraperStudio** [comment]
The `questions` method returns a `morphMany` relationship so you can just call any Elouquent methods on those.

Might add helper methods one day, but not for now.
